apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: my-grafana-operator
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: olm-operators/grafana
    repoURL: 'https://github.com/chetan-rns/gitops-cluster-config'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true