apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: image
    repoURL: 'https://github.com/chetan-rns/gitops-cluster-config'
    targetRevision: HEAD