apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: console
    repoURL: 'https://github.com/chetan-rns/gitops-cluster-config'
    targetRevision: HEAD